### ISSUE TITLE
KMK/QMK based design (feature request)

### ISSUE THREAD

**Issue by oemsysadm** [aeberbach/A1200KB#4]
There are various teased products out there, from replacement keyboards (like the kipper2k), to usb converters like the keyrah, but most of it seems like vaporware or at best is almost impossible to get a hold of.

For those of us who are interested in building emulators or FPGA based systems in a new A1200 case from A1200.net, there aren't many options for keyboards out there.

That said, DIY mechanical keyboards are relatively easy to do, but most of us don't have the knowledge to create a PCB; especially if it needs to conform to an existing design that a lot of us don't have access to directly measure.

How simple would it be to convert your existing PCB design to create something with a simpler column/row matrix that can easily be connected to a cheap micro controller flashed with one of the common keyboard firmwares, like KMK or QMK?

As an aside, what profile key caps did you use for the keyboard you have pictures of in this repository? It looks like DSA or something like that. I would assume not all key cap profiles will work for this.

**Comment by aeberbach** [comment]
I did use DSA caps, just because they are my favourite and I could put together a complete set at Signature Plastics. Any MX-compatible set should be fine including OEM (most common) and SA.

I don't know exactly how hard it would be to make this a KMK/QMK design. This is a reverse-engineered reproduction of the original C= product and it relies on the Amiga's onboard keyboard decoder to interpret the 31 signals from the keyboard. That said, the connections are basically a matrix with horizontal and vertical rows with dedicated lines for about seven of the keys such as CTRL, Amiga, ALT etc. I have not done anything with that controller though...
